### ISSUE TITLE
Bug report | READ ASAP

### ISSUE THREAD

**Issue by Djmeowzle** [InZidiuZ/legacy-assets-issue-tracker#134]
**Reporter:**
Djmeowzle#3106

**Summary:**
After rigorous testing in GTA:O and FiveM. I've come to find out that the ETR1 has no back window, and a metal panel covering where it is... it is bulletproof. This can't be something that belongs in legacy, and any of these cars on the street should be removed and the owners compensated the full price of the vehicle.

**Screenshots:**
No screenshots but if you look at any image of the car you can see it has the backplate, as well as inside the car there is a carbon wall directly behind the driver.
**Notes:**
This needs to be fixed ASAP, as it can lead to being abused by people to gain an advantage in certain situations.

**Comment by TwoplePop** [comment]
Yea it can be used in situation to gain advantage. But cars can only withstand a certain amount of bullets. Just because there is no back angle doesnt mean that it doesnt belong in legacy. The infernus local car barely has anything in the back. There are many pdm cars that have metal sheets in the back as a customizable.

**Comment by Djmeowzle** [comment]
Customizable is different, and I've tested them multiple times, they're all able to be shot through, with full armor on a car, it can basically be the same as having a tank, at least having near the same protection.

**Comment by TwoplePop** [comment]
the Hermes is a tank. ETR1 is just a regular super car with the engine in the front which should still be damaged easily. If anything, the Hermes is more of a tank. The back plate might prevent bullets from hitting but it will damage the car heavily since the trunk and engine are weak points. The damage script in legacy is also very different from gta. Yesterday, I shot only 40 shots in my fully armored elegy retro and it blew up. This was in Legacy.

**Comment by Karpenkooo** [comment]
Hey, 

After some testing, I've come to the conclusion to keep this vehicle in the server. The fuel cell in the back does provide cover however I do not see this being an issue on a rare supercar which shouldn't be used for criminal activity. However, if I see a change in the use of the ETR1 then I may remove it from PDM. 

_**Karpenko - OP FW Assets Developer**_
