### ISSUE TITLE
Flash GT Trunk! Really?

### ISSUE THREAD

**Issue by maguhd** [InZidiuZ/legacy-assets-issue-tracker#174]
**Reporter:**
MaguHD#8534
https://steamcommunity.com/id/maguhd/

**Summary:**

Are you kidding me?
https://prnt.sc/rut05b
https://prnt.sc/rut18c

BTW top speed is still limited @168mph

**Comment by TCruxer** [comment]
Hey,

The car acceleration/speed have now been adjusted and should be fixed in the upcoming updates.

As for the low trunk space please refer to the other issue tracker [over here](https://github.com/InZidiuZ/op-framework-issue-tracker) as this is not related to the asset.

**Cruxer    _Lead Asset Developer_**
