### ISSUE TITLE
Customization on import cars

### ISSUE THREAD

**Issue by meeksbtw** [InZidiuZ/legacy-assets-issue-tracker#24]
**Name:**
Meeks#5150

**Summary:**
I think you're aware but all of the import cars except one or two have no cosmetic upgrades,  especially all of the top tier cars, GTR, Ferrari, Lambo, etc. I don't know if/when this will/can be fixed by you or if this is the mod's problem but, it would make the exclusive cars ten times better. For example, i'm not sure what exact model GTR Karpenko used but if its the most downloaded one (link below) then, it has some of the best customization, (LibertyWalk Nismo RocketBunny)

**Link:**
https://www.gta5-mods.com/vehicles/2015-nissan-gtr-nismo-yca-y97y

**Reason:**
Making exclusive cars more customizable and unique.

**Comment by Karpenkooo** [comment]
Hey

This is the same model however i've removed the LB Kit as the wheels don't get offset when you apply the kit. However we're working on car offsets so once that's done the GTR witll have a LB Kit. However there's many cars that cannot be added due to being badly optimized.

_Karpenko_

_**OP-FW Vehicle Developer**_
