### ISSUE TITLE
[imports/wheels] New Wheel Categories

### ISSUE THREAD

**Issue by PatelBhai03** [InZidiuZ/legacy-assets-issue-tracker#251]
**Name:**
Patel Bhai | Vish Patel#9166

**Summary:**
I think RP'ers are now Fed up of seeing Same customization since the past 1 year or so and now maybe you guys should add
New Wheel categories which are available in GTA 5 Online
For Eg- (categories)
Benny's originals
Street  
**Link:**
No Link 

**Reason:**
This might encourage people from buying and PDM cars as well and people can get a bit creative as well

**Comment by joevapes3** [comment]
This would have to be done from the Los Santos Customs script and cannot be done from assets. I will reach out to the script dev team and see about getting this added to the Los Santos Customs script, as there is other features/mods I'd like to see added for the vehicles as well. Especially since this a vanilla asset that will utilize resources that are already being loaded.  Thank you for your suggestion.
