### ISSUE TITLE
[imports/police] Adding Offroad motorcycle for Police

### ISSUE THREAD

**Issue by Khasnuwr** [InZidiuZ/legacy-assets-issue-tracker#321]
**Name:**
arif#1111 , [Steam Profile](https://steamcommunity.com/id/smarifmahmud9/)

**Summary:** 
Suggesting to add an **Off-Road** Police motorcycle to add more aesthetic police patrols, chase pursuits etc.

**Link:**
1. [Maibatsu Manchez](https://gta.fandom.com/wiki/Manchez)
2. [Maibatsu Sachez](https://gta.fandom.com/wiki/Sanchez)
3. [Nagasaki BF400](https://gta.fandom.com/wiki/BF-400)

**Reason:**
As there are off road places where police patrols, responds emergency calls, participates chase pursuits. It is required to use an off road bike in off roads and hills.
.

**Comment by pepaj420** [comment]
there's already good model of police bf400: https://www.gta5-mods.com/vehicles/hakucho-police-bike and I strongly support this idea, because police has only sports motorcycle, which looks strangly jumping around hills after some sanchez, because there's no other vehicle to do it.

**Comment by joevapes3** [comment]
Currently at this time the only bike unit that PD is going to have is the 2014 Kawasaki that is already implemented. It was made so that the vehicle had excellent off-road capabilities and has been tested to reach all the places mentioned in your suggestion. All motorcycles from vanilla to exclusive have been balanced around each other on this latest handling update that was pushed a few days ago. I will keep an open mind and eye out for a possible dedicated off-road vehicle, and discuss it with the other asset developers to see if something could be added in the future. I appreciate your suggestion.
