### ISSUE TITLE
[vehicles/damage] Weapon damage to vehicles and Crosshair removal

### ISSUE THREAD

**Issue by Retrizz** [InZidiuZ/legacy-assets-issue-tracker#475]
**Name:**
Who is suggesting this? Please include discord name.
Harry.#6804
**Summary:**
Write a short summary of what your suggestion is about.
Vehicle health.
vehicles should disable after taking a REASONABLE amount of damage rather than blowing up after 2 mags from a combat pistol.

Vehicle gunplay.
shooting out of a vehicle should be made harder by removing the crosshair while shooting from a vehicle and recoil should be increased, and maybe if it is possible, the addition of increasing speeds=even higher recoil.
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Vehicle health.
It would be a good addition to stop the current meta which is using a neon or any other electronic car that has a rather big spoiler and considering it is electric, it doesn't explode. Making cars disable can turn car fights to foot fights and still give the guys in the broken vehicle a chance, also, shooting a car twice into its windows doesn't make realistic sense for the vehicle to start leaking. 

Vehicle gunplay.
Giving cars the mechanic to disable after a REASONABLE amount of shots will mean that car fights will last a little longer and with the current recoil and crosshair status for the server I feel like it will be "easy" for some people to fight in cars, but the suggestion   to remove crosshair and increase recoil will still make car fights hard to do, and will give the people fighting more of a chance to live longer than 60 seconds, rather than blow up after 20 seconds.

**Comment by Nuziatella** [comment]
> **Name:**
> Who is suggesting this? Please include discord name.
> Harry.#6804
> **Summary:**
> Write a short summary of what your suggestion is about.
> Vehicle health.
> vehicles should disable after taking a REASONABLE amount of damage rather than blowing up after 2 mags from a combat pistol.
> 
> Vehicle gunplay.
> shooting out of a vehicle should be made harder by removing the crosshair while shooting from a vehicle and recoil should be increased, and maybe if it is possible, the addition of increasing speeds=even higher recoil.
> **Link:**
> If there are any links to what you're suggesting, please add them here.
> 
> **Reason:**
> Why would your suggestion be a good addition to Legacy?
> Vehicle health.
> It would be a good addition to stop the current meta which is using a neon or any other electronic car that has a rather big spoiler and considering it is electric, it doesn't explode.
This is a gtav mechanic. Server managers/communities can ban the use of these types of vehicles for shoot-outs.

>Making cars disable can turn car fights to foot fights and still give the guys in the broken vehicle a chance, also, shooting a car twice into its windows doesn't make realistic sense for the vehicle to start leaking.
**-- I'm not able to reproduce which vehicle has this issue. It's possible a collision was removed from the spoiler which is allowing bullets to hit the tank. You'll need to provide example vehicles.**
> 
> Vehicle gunplay.
> Giving cars the mechanic to disable after a REASONABLE amount of shots will mean that car fights will last a little longer and with the current recoil and crosshair status for the server I feel like it will be "easy" for some people to fight in cars, but the suggestion to remove crosshair and increase recoil will still make car fights hard to do, and will give the people fighting more of a chance to live longer than 60 seconds, rather than blow up after 20 seconds.
**-- Cars do disable after a reasonable amount of shots depending on the weapon. Large caliber bullets will disable a vehicle quickly, smaller caliber will take longer. Shooting gas tanks will cause them to leak quickly regardless of caliber. Continued shots will cause a failure with a chance of catastrophic (explosion). 
-- Crosshairs will not be removed. There is a plethora of utilities, monitor settings, and do-it-yourself solutions to put them back. For the very small percentage of the community that do not know how or choose not to; they would be at a permanent disadvantage.** 

Is the issue here meta related? Do people chose to use cars and thus believe cars are the better way for shootouts? Or is being in a vehicle better? Is this just poor planning for a shootout? No-one has yet to produce evidence as to the why. Just circumstantial or opinions.  In a closed controlled environment even a single person posted in a good location could quickly disable and down multiple persons in an electric vehicle (or any vehicle outside armored pd vehicles) do to their mobility in the 3-D space while the individuals were locked into their seats in a vehicle. In the occasions where the individuals in the vehicle were not downed they were forced to flee.

**Comment by Retrizz** [comment]
-- I'm not able to reproduce which vehicle has this issue. It's possible a collision was removed from the spoiler which is allowing bullets to hit the tank. You'll need to provide example vehicles.

-you can literally make cars leak while doing chop by shooting the driver and the bullet hitting the windows

-- Cars do disable after a reasonable amount of shots depending on the weapon. Large caliber bullets will disable a vehicle quickly, smaller caliber will take longer. Shooting gas tanks will cause them to leak quickly regardless of caliber. Continued shots will cause a failure with a chance of catastrophic (explosion).

-They do not "disable" after a "reasonable" amount of shots, they begin to leak after a handful and blow up after maybe a mag depending on the car. What I mean by the car disabling is the engine cutting out so it is no longer usable

-- Crosshairs will not be removed. There is a plethora of utilities, monitor settings, and do-it-yourself solutions to put them back. For the very small percentage of the community that do not know how or choose not to; they would be at a permanent disadvantage.

-For this point, as long as admins can do their job if anyone gets caught using one of these it is a bannable offence, which Sia was saying in the gang discussion when this talk came up a few days ago. 

--Is the issue here meta related? Do people chose to use cars and thus believe cars are the better way for shootouts? Or is being in a vehicle better? Is this just poor planning for a shootout? No-one has yet to produce evidence as to the why. Just circumstantial or opinions. In a closed controlled environment even a single person posted in a good location could quickly disable and down multiple persons in an electric vehicle (or any vehicle outside armored pd vehicles) do to their mobility in the 3-D space while the individuals were locked into their seats in a vehicle. In the occasions where the individuals in the vehicle were not downed they were forced to flee.

-People choose to use cars because only having foot fights isn't always going to be fun, it will get repetitive and boring, same way that only having car fights will be repetitive and boring. The issue is unless you have a neon you literally cant car fight because you blow up too quickly. The only reason why the neon is or was classed as a meta car is because it didn't leak which is good because it isn't meant too.

-the only way a single person is able to take out a neon with 4 people inside is if 1 he is using a god angle 2 he is using an AR or something high calibre and 3 you would have to make the car leak which is stupid because the car is electric for a reason. An electric car shouldn't have to leak, it should disable

**Comment by DaxterPancake** [comment]
After months of using this new car system, I think it is now safe to say that the damage system for petrol cars is/was/continues to be an issue. 

People are finding work arounds to the system put in place by abusing electric cars because of how easy the normal vehicles are exploding.

Electric cars are being used as they don't explode as fast as the petrol vehicles, they also NEVER run out of gas despite the fact they are leaking fuel.

A better, more RP friendly solution that I am proposing is having the car disable at the current speed they explode and then explode after awhile or after shot with a certain amount more bullets. This proposal allows for the continuation of RP instead of the RP being over as soon as the engine lights on fire after a clip of your pistol. This PoV comes from both an officer and a criminal. In a setting where officers are firing on one or two vehicles, it's multiple clips going into one car at one time, exploding the car REALLY FAST.
Now, I wholeheartedly agree that car shootouts are an issue and that more foot fights need to happen, but as it stands right now, the work around people are finding is worse than having to deal with a variety of vehicles.
I'd much rather have to run after a group of people when their car disables than have them all die in an explosion and the RP is over right there and then.

**Comment by Nuziatella** [comment]
It's on Ben's list to add explosion as an option for electric vehicles on catastrophic failure. This will cause them to react the same way petrol vehicles do depending on which level of failure has occurred. A new damage system is possible with a revamp of connected dependencies. Until then though, the goal is to have electric vehicles react the same as petrol vehicles. 

One thing to note, vehicles that can explode, only explode on what RAGE considers to be "catastrophic" failure. The way it's currently tuned is your "intention" needs to be to cause the explosion. Generally speaking all vehicles, except for a few outliers, take 3 shots to cause fuel leakage and another 2-3 to cause it to explode. The body and engine vary quite a bit but generally, without the use of powerful guns, most vehicles take an unrealistic amount of bullets to cause "catastrophic" failure. Going back to spring of this year when I had a bunch of people in the test server driving and shooting at each in various vehicles, it became quite obvious that the only time a vehicle were to explode is when the shooter _intends_ to cause the explosion. 

Now this isn't to say there isn't some bugs somewhere. Also some vehicles had collisions removed from the backend which could be unintentionally allowing bullets to pass through and hit the tank where normally there would be a collision to stop that. But this would come down to people reporting vehicles that have this bug so the collision can be re-added.
