### ISSUE TITLE
Green Wonderland Menu / TV Suggestion

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/legacy-assets-issue-tracker#496]
Assurance:
Yes

Summary:
Would like to add a menu (place static image on our TV) in Green Wonderland to help customers with availability and pricing

Reason:
This would help customers easily see what they can purchase, how much it costs, and how often they can purchase to remain within the city laws and guidelines. This would also enhance the ambiance of the shop as it is something unique that would draw a customer's attention.
![New TV 8](https://user-images.githubusercontent.com/81762234/132779990-f2642d90-ecd7-48ae-b2f0-707176e37db6.png)
![Menu 8](https://user-images.githubusercontent.com/81762234/132779992-0be9d5b0-fd9a-43d4-ba4b-d2e97eee71ca.jpg)

**Comment by DaxterPancake** [comment]
This won't be added due to a few things:

- Assets are shared across all subdivisons and their pricing may be different
- You can just continue to RP and talk to the people who come into your store to tell them your pricing
- In the future you could (possibly) have a shop like bean machine does which may have more items so then we'd need to continue updating the poster, etc. That's just not realistic with all the work we already have to do.

Won't be doing this as of now.
