### ISSUE TITLE
Choppers make banging sounds to remote players when driving.

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/legacy-assets-issue-tracker#542]
**Reporter:**
Who is reporting this? Please include discord name.
MetaHatter#0001

**Summary:**
Write a summary of what you're experiencing.
Motorcycles, specifically choppers make loud banging noises to remote players.  The effect sound does not play to the person riding the bike only those in a 5 block radius.  Video example attached. You can hear it coming from a MILE away.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy

https://user-images.githubusercontent.com/84351858/143999739-378e113a-7649-4abb-ba0a-47878d7414db.mp4

.

**Comment by joevapes3** [comment]
Unfortunately with vanilla vehicles there is no way for us to control the npc awc audio with them, as they're vanilla assets, and InZidiuZ has decided that it's a waste of resources at this time to stream them. With addon motorcycles, the sounds they use are vanilla sounds as well, so once again we'd not be able to adjust them either, and giving that addon motorcycles their own custom sound at this time isn't an option either. Since no creator as made addon bike sounds outside of one street bike sound, since I stay on top of all custom engine audio creators there are. Closing this issue out, and if you have any further questions about the matter, feel free to reach out to me for further explanation.
