### ISSUE TITLE
[maps/*] MyDogHinnie Memorial Suggestion

### ISSUE THREAD

**Issue by sleighwhite** [InZidiuZ/legacy-assets-issue-tracker#544]
**Name:**
sleighwhite#8707

**Summary:**
After the sudden and devastating passing of a dear friend and long-time player on the server, MyDogHinnie, I would like to suggest that we add a memorial to the server in her honor. One of her characters, Kate Knight, was a long time employee at Pillbox Medical so that might be one area in which we could add something in her honor (like a plaque or something). Another idea might be to have a Memorial wall that could memorialize multiple people as we've also lost another player, Jake. 

**Link:**
I found this on a GTA Mods site, so maybe it could be something simple to quickly add: https://www.gta5-mods.com/misc/memorial-wall-ymap-fivem

**Reason:**
I think it's important to remember that behind our screens, players are real people with real lives that make real impacts on one another every single day. I think that this can help give members of the community something to visit to help them with their grief and mourning.

**Comment by DaxterPancake** [comment]
This is 100% already in the works, thank you for your suggestion. Feel free to reach out to Lunar if you have more ideas.

**Comment by djclark21** [comment]
I was wondering, as part of a memorial for Kate, is there a way to add a decal for her for EMS to wear with their uniform? It would be like an arm band. Black. With white lettering and the only thing on the band would be her call sign? Since we've retired the callsign, it's forever hers and this would be a nice way to acknowledge her on a daily basis. Not sure if it's possible and I apologize if this isn't the right place to post this. Thank you.
