### ISSUE TITLE
[vehicles/vgt12] Aston Martin GT12 handling issues

### ISSUE THREAD

**Issue by Luspect** [InZidiuZ/legacy-assets-issue-tracker#550]
**Name:**
ItsJim#4872

**Summary:**
The Aston Martin GT12 i think is not quite up to par for the price point. I paid approximately 160k after upgrades and the car struggles to break 160mph on a straight. I also am unable to hear the turbo. The acceleration is extremely mediocre and the vehicle tips around corners. I would greatly appreciate if someone could check out all the new vehicles because not a single one I have come across goes over 160 on a straight consistantly. I have so far seen the Evo, the Camaro, the integra, and the 4 door merc. All same exact speed caps. Especially with the cost of the aston, i personally feel the performance should be better

**Comment by Djmeowzle** [comment]
I have a Vanilla Rapid GT Classic, Based on the Aston Martin V8 Vantage. And that hits around 170~ on a straight and has none of those problems. That being said, yes, I believe your car does need some significant upgrades. Maybe grippier tires and some better acceleration.

**Comment by joevapes3** [comment]
Tested the vehicle out in the opfw test server fully upgraded, with engine level 4, turbo, and transmission, and I was able to hit 185mph on a flat and about 195 abusing physics which is a few mph faster than it's intended to be. The acceleration also seems fine as well. So I am not sure how your stuck at 160mph, but more than likely you should go check your upgrades again in LS customs, as I don't believe you have them all on there or they might not of saved on there. Since that speed is what it would do with no engine upgrade on it. Will leave this issue open to await your response to see if that's the case and then close it afterwards.
![FiveM_b2189_GTAProcess_tWpo5M1IIY](https://user-images.githubusercontent.com/44896032/146985137-7bbf83c9-0dfa-4665-855c-1ba4293d39c4.jpg)
.

**Comment by joevapes3** [comment]
Since there has been no response from you here. I am going to close this issue out. As we were unable to replicate this issue. The vehicle with full upgrades is currently above the balance level and will be lowered soon to match the the other vehicles in it's class.
