### ISSUE TITLE
Suggestion: PD Liveries - add white as base color option

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/legacy-assets-issue-tracker#569]
**Name:**
_Who is suggesting this? Please include discord name._
(me), panpawn#8183

**Summary:**
_Write a short summary of what your suggestion is about._
Add frost white (metallic) as another base color option for SASP livery.

**Link:**
_If there are any links to what you're suggesting, please add them here._
[Here's an example](https://i.imgur.com/Ao0YmOZ.png) 

**Reason:**
_Why would your suggestion be a good addition to Legacy?_
It would add more variation to the liveries, and white/black also looks really good.

**Comment by joevapes3** [comment]
I created the liveries so that they're transparent and can be painted in LS customs. That way once pd vehicles are owned, sub divisions can individually decided which color their vehicles should be in their respective departments, and they would save when they park them. So for now if your pd command allows you to have a different color paint, you can ask them if you're able to paint it to that color. Though currently while we don't own our vehicles yet, you'll need to paint your vehicle each time you go on duty.
