### ISSUE TITLE
[Vehicles-Handlings] Handling Suggestion: Ellie Drift Handling changes

### ISSUE THREAD

**Issue by PoshoGH** [InZidiuZ/legacy-assets-issue-tracker#575]
**Name:**
Posho#9999

**Summary:**
Changing the handling for the ellie drift import

**Link:**
N/A

**Reason:**
The ellie drift was changed to where it only wheelspins all the time instead of when it used to drive well and be very slippery on the corners. If you launch the car into a wheelie often the wheels just pop completely.

**Comment by joevapes3** [comment]
So I will take a look at the Ellie's handling meta, but nothing has changed on it that vehicle in over a year. So not sure how it changed recently, but meta wise it didn't. Either way I'll check it since all of our drift vehicles have similar handling values, and I'll make sure it's on par with the others. I'll update this thread once I've taken a look at it.

**Comment by joevapes3** [comment]
So after further review the asset has the standard drift handling that all other drift vehicles share. However it hasn't been changed in over a year so if it feels any differently, then it's probably just cause you haven't drove it in a while. Though nothing actually changed. I will be reviewing all the drift vehicles handling soon tm, and at that time I will take a look at this one as well. Thanks for reaching out and I will be closing this thread at this time.
