### ISSUE TITLE
Salieri's Bar Improvement Suggestions

### ISSUE THREAD

**Issue by PhoebeGunn** [InZidiuZ/legacy-assets-issue-tracker#598]
**Name:**
ObsidianPsyche#1547

**Summary:**
After running Salieri's for nearly 2mos there are a few things we hope to be added to help us continue on our road to success. These things include:
1. Add an ATM so customers don't have to travel to the grocery store a few blocks over.
2. New food item sold by Salieri's: Pizza (slices or whole) to bring a new and heavily desired food item to the city. 

**Reason:**
ATM Near front far right door: This is a request simply to improve visits for our patrons. We are often asked if we have an ATM on premises and would like to be able to offer that amenity if at all possible. 
![image](https://user-images.githubusercontent.com/96025189/157746536-27b468ce-0a34-43e6-a3bc-baf17415c91e.png)

Pizza Addition: 
While Salieri's was originally intended as a bar we have been running it as a Diner & Bar in the hopes of offering new and exciting food options to citizens. Without refrigeration though it has become harder to purchase bulk items from local sources to sell as part of our various Italian themed dining options. Fries sold as Italian Poutine, Burgers sold as Italian Sausage Burgers, Sandwiches sold as Gabagool Sliders. We've even had Waffles and fruit served as part of a brunch menu. Despite our efforts there is one question we are asked the most; "When will you have pizzas to sell?" We would love to be able to answer that cry for pizza with our own slices and/or whole pizzas sold exclusively at Salieri's. Let us bring a taste of the old country to Los Santos! 

Our pizza offerings could come in one or both of two options

Slices:
![image](https://user-images.githubusercontent.com/96025189/157748068-7b640329-5383-4f7f-b202-868278fc6050.png)

and/or Whole pies:
![image](https://user-images.githubusercontent.com/96025189/157748098-f5eaf827-a8a9-45df-8280-b6d2277b0eb9.png)

Slices could be single use. And provide hunger relief as well as a small portion of stress relief as greasy delicious cheesy goodness should. 
Whole pies could be multi-use (8 slices) and each use could provide the same amount of hunger and stress relief as a single slice would. 
With a plain cheese style pizza image the options for customers requests are endless! Pineapples? Anchovies? Classic Pepperoni? Salieri's can make it! Providing not only a delicious new food option, but also encouraging great RP interactions; and maybe even some arguments over what toppings are best?

With these new options we would be able to offer delivery and seated dining experiences to customers helping us to expand our business into a new and highly desired restaurant option for Los Santos. 

**Summary:**

We hope you'll consider these additions! We whole heartedly believe these changes will bring great RP interactions and excitement to the city.  We know it's something citizens have been hoping to have for a long time and we would love the opportunity to be able to bring this request to all of Los Santos.

**Comment by KCnSC** [comment]
I would eat the hell out of some pizza

**Comment by kaycorriher** [comment]
I have enjoyed every interaction I’ve had at Salieri’s and love the effort the owners have put in to not make it like every bar in the city. The RP of getting a strawberry waffle on their opening day was just the start of what the bar has been providing until the food started spoiling and they lost all their supplies. 

I would love to see pizza or an entire Italian menu at the venue. No matter what tho i will continue coming back to listen to the staffs kitchen chatter. “I dropped the spoon. Put it on the plate, they won’t know”

**Comment by ShaquilleOatmeal007** [comment]
I would love to become a pizza boy and deliver pies all over the city. Might have too steal a few for myself too!

**Comment by vol5** [comment]
First off... Burgershot does not have any reasonable competition when it comes to food product. This could assist that and add value with more crafting. Crafting is huge and 100% should be further expanded to other places. Also I find it WILD that a universe "based in America" does not have a pizza product and this would be time to add that value. There is nothing like a group of Italians cooking up pies in the back yelling and serving them to people..... the RP would be fucking amazing! That is a beautiful sight. I feel it would be beneficial to make it something unique and different in terms of product benefit/effect to differentiate the product from all the other food items. Currently they all have the same and boring variables changed. Hp, Armor, Hunger, Thirst, Stress. (unique = different effect that is not inside those 5 vertices to play with) The goal being products you get through rp drive more interaction since they are better outside of just degradation incentivization and the standard food fill of hunger/thrist/stress. Big T and the team are smart individuals. You could come up with something that is not broken but unique. If you would not want to look into making it unique fine but at least make it damn good.....

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/161478527-adf9fbed-adae-4f96-adb8-f0365d1b17fd.png)
Soooo food will take me a bit. Not going to do pizza for this since we are doing pizza place.

**Comment by DaxterPancake** [comment]
Closing this due to the atm being added, if you'd like the addition of custom food you would need to request that [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
