### ISSUE TITLE
Tunershop Warrener

### ISSUE THREAD

**Issue by HowieTheBrave** [InZidiuZ/legacy-assets-issue-tracker#602]
**Name:**
Who is suggesting this? Please include discord name.
Howie/Rio - kachoWie#2302

**Summary:**
Changing the Tunershop Warrener to a normal driving car, not drift, and currently it can barely even drift. Ive spoken to a lot of people who like the Warrener truck and want to own it, but end up not buying it because its a drift car.

**Link:**
https://static.wikia.nocookie.net/gtawiki/images/f/f0/WarrenerHKR-GTAO-front.png/revision/latest?cb=20210720164531

**Reason:**
There are people who want this car and really like it, to the point of it being the only car they actually want from the tunershop lineup, but end up not getting it because of the fact that it is a drift car.

**Comment by HowieTheBrave** [comment]
Any chance to get this looked at?

**Comment by joevapes3** [comment]
This vehicle was meant to be a drift car and will stay as such, as the drift community has asked for a new drift vehicle for quite some time and that car was designated for such. Though yes it's handling was in a bad place due to it's tuner car status being difficult to work with. However I completely redid the handling and now it's drives much better and drifts as it should very strong. This change should be live in the next server update.
