### ISSUE TITLE
Fire Department building

### ISSUE THREAD

**Issue by B7ackPanda** [InZidiuZ/legacy-assets-issue-tracker#609]
**Name:**
Who is suggesting this? Please include discord name.
Panda#4916
**Summary:**
Write a short summary of what your suggestion is about.
my suggestion is for a fire department building
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.lcpdfr.com/downloads/gta5mods/misc/19387-sandy-shores-fire-station-upgrade/
**Reason:**
Why would your suggestion be a good addition to Legacy?
With cars now burning for much longer than they used to and EMS having an actual fire department, I believe it would be nice for the fire department to have somewhere nice to station other than the already existing buildings or hospital. This asset has a classroom which the fire department and all EMS can use for training.

**Comment by DaxterPancake** [comment]
This interior/map isn't very nice in my opinion, is there any other option you can find?

**Comment by B7ackPanda** [comment]
So we had a little look around and we also like this one:
https://ultrunz.com/store/SandyFire

we woud be perfectly willing to pay for if it gets aproved

**Comment by antihero6713** [comment]
We already had a version of a fire dept there, but since we have no fire department why would we add this with out a job for it?

**Comment by B7ackPanda** [comment]
> We already had a version of a fire dept there, but since we have no fire department why would we add this with out a job for it?

EMS has a fire department yes we don't have a job title for it and EMS does have the fire engine

**Comment by antihero6713** [comment]
If the job title becomes a thing where you can actually fight fires i will add the sandy fire dept back in that we had for now we will close until a fire fighter job exist.

**Comment by mastersamii** [comment]
While I understand the concerns of there being no actual fire department separation there is currently a department in EMS that Is the fire department we fall under EMS cause we are still paramedics at the end of the day.

We work with constant fires from car and gas station explosions which btw fires last longer now and PD has called us several times to put out fires for burning cars.

As well the fire department covers the search and rescue side of things which if you don't know is a lot!
I for one think that if PD can get a highway building then we EMS who are the fire department and are willing to pay for the building should be at least considered.

Actively we have several tests and certifications for the FD as well we also require bi-weekly training so having our own building in Blaine county would be extremely helpful not only for classes but also for training as a lot of our training happens in sandy.

The FD also goes over basic med for all of PD and is working on reworking the swat med class and even more, things are being worked on as we speak. It would be extremely convenient to have a place in sandy to call home and teach others rather than sitting in the sand or on the roof of MRPD.

**Comment by mastersamii** [comment]
![218_20220402154340_1](https://user-images.githubusercontent.com/77824478/163435772-d239e8c6-622f-4f27-b288-26b5938a8df8.png)

**Comment by DaxterPancake** [comment]
I also agree with this.. The Fire Department is quite big in the international server and obviously the other ones. I don't believe it's fair to require them to have a job when being an EMS/Doctor IS the job that they would have. It's the same department just different divisions. Just like PD has. Highway Patrol isn't an actual job, nor is FIB, nor is Park Rangers, yet every single one of them have an interior just for themselves. 

I don't think it's fair to handicap them behind a job like that.
