### ISSUE TITLE
[maps/gamble_hideout] Underground Casino Additions

### ISSUE THREAD

**Issue by FB-Toobtv22** [InZidiuZ/legacy-assets-issue-tracker#628]
Name- FB-Toob_tv22#0327 

Summary - 1 Billboard sign with logo, Empty Current Billboard on wall with logo, Logo on Main door, I would also like to add a map marker for the location of the casino. I can pay for this matter to be handled in a timely manner. Thank you, Zach Link - https://cdn.discordapp.com/attachments/671092162930278446/976613622912544838/Casino_Night_Club_logo.png  (LOGO), https://cdn.discordapp.com/attachments/480419812787355668/976489227401453618/Casinonightlocation-logo.png (Wall billboard, Door Poster shown, The billboard I would like to have the logo is directly above the wall billboard) 

Reason - I think this would be a great addition to Legacy due to the fact we,re in the city everyday trying to find ways to better people as well as create jobs for the people of Legacy. As well as it will make it much easier for people to find the casino location since it is in a back alley. Thank you for your time, Zachary!

**Comment by MetaHatter** [comment]
Reformat for readability

Suggestion: 
Name- FB-Toob_tv22#0327 

Summary 
1 Billboard sign with logo, Empty Current Billboard on wall with logo, Logo on Main door, I would also like to add a map marker for the location of the casino. I can pay for this matter to be handled in a timely manner. 

Thank you, Zach 

Link 
https://cdn.discordapp.com/attachments/671092162930278446/976613622912544838/Casino_Night_Club_logo.png (LOGO)
https://cdn.discordapp.com/attachments/480419812787355668/976489227401453618/Casinonightlocation-logo.png (Wall billboard, Door Poster shown, The billboard I would like to have the logo is directly above the wall billboard) 

Reason
I think this would be a great addition to Legacy due to the fact we,re in the city everyday trying to find ways to better people as well as create jobs for the people of Legacy. As well as it will make it much easier for people to find the casino location since it is in a back alley. Thank you for your time, Zachary!

**Comment by DaxterPancake** [comment]
Billboard is an in character thing, you have to find out who you can pay for them to be made.

Map marker is not an asset issue.

Is this not an underground casino and therefore does not make sense to be an actual buisness?

**Comment by FB-Toobtv22** [comment]
Then do explain why I have to have a gambling license to own the business? Sent from Mail for Windows From: DaxterPancakeSent: Saturday, May 21, 2022 12:42 AMTo: InZidiuZ/legacy-assets-issue-trackerCc: FB-Toobtv22; AuthorSubject: Re: [InZidiuZ/legacy-assets-issue-tracker] Underground Casino Additions (Issue #628) Billboard is an in character thing, you have to find out who you can pay for them to be made.Map marker is not an asset issue.Is this not an underground casino and therefore does not make sense to be an actual buisness?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FB-Toobtv22** [comment]
Underground or not it is a 100% legal casino therefore can be made into a business. Hence why I am asking for a marker. Sent from Mail for Windows From: DaxterPancakeSent: Saturday, May 21, 2022 12:42 AMTo: InZidiuZ/legacy-assets-issue-trackerCc: FB-Toobtv22; AuthorSubject: Re: [InZidiuZ/legacy-assets-issue-tracker] Underground Casino Additions (Issue #628) Billboard is an in character thing, you have to find out who you can pay for them to be made.Map marker is not an asset issue.Is this not an underground casino and therefore does not make sense to be an actual buisness?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by antihero6713** [comment]
Going to close this. Make another github if you still want this still
