### ISSUE TITLE
PD Vehicle Spawns - Suggestion

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/legacy-assets-issue-tracker#650]
**Name:**
Dex#5879

**Summary:**
Moving the PD vehicle spawn points to repair points at different departments.

**Link:**
[Example Image](https://i.imgur.com/K0rc7ax.jpeg)

**Reason:**
PD Vehicles are owned now, which means if stored with damage/local impounded/whatever the case, that means they can be brought back out with that same damage. At MRPD, they are spawned just outside of on the repair spots in the parking garage. 

My suggestion, is that the spawn point for the vehicles at MRPD be moved into the box with the stripes (image above), so that the /repair command can be used for vehicles that are fully disabled. Or maybe just slightly increase the radius of the repair spot, to include that section outside of the box.

Now with this, the BCSO vehicle spawn might need to be moved to the corner of the building where the repair spot is, so that if they bring out a fully damaged vehicle there they can also repair it to a drivable state.

**Comment by twooot** [comment]
This would block the spawner of the other vehicles. If your car is too fucked up to be driven to the next repair spot, then you **should not** be using /impound and retrieving it at the garage, since that's borderline power gaming. You should call a tow and get it repaired at a mechanic shop. And if you can still drive your car you can drive to the next repair spot or optimally to a mechanic since we are here to rp not avoid rp by using /repair
