### ISSUE TITLE
[peds/*] Badge From New Highway Hat onto Uniform

### ISSUE THREAD

**Issue by rustyjohn1** [InZidiuZ/legacy-assets-issue-tracker#661]
**Name:**
RustyJohn1#6353

**Summary:**
so from the linked picture below the new badge that is on the hat could we get this onto all relevant highway patrol TOPS.  as the current badge is very outdated and doesn't match. 

**Link:**
https://i.imgur.com/RnMo9Lc.png

**Reason:**
Would continue to add to highway RP. which people are enjoying

**Comment by DaxterPancake** [comment]
The hat doesn't need to match the brand new uniform that was just custom made for you in order for highway patrol to be able to have more fun roleplaying.

So, in saying that, this won't be done at this time. If we decide to update uniforms in the future we may reconsider. 

Thanks!

**Comment by DaxterPancake** [comment]
Additionally, I am unclear on what the uniform for Highway Patrol actually is now since it has gone back and forth for awhile now. When it has been officially decided what the uniform/colour scheme is please reach out to me so the team knows WHEN additions are being made what we should be making.

Cheers!
