### ISSUE TITLE
Suggestion - Items on our block

### ISSUE THREAD

**Issue by MrSnowSar** [InZidiuZ/legacy-assets-issue-tracker#709]
### Name

$now#1588

### Summary

(In the name of Ace Cartel)

We've seen that there's a few groups that have gotten some custom items put down, such as trees, bushes, sand bags, etc. So we wanted to request some as well. 

We are located on Fudge Lane and we've had that block for months now and we wanted to brighten it up a little by placing down some "custom" items. If possible of course. 

We aren't really sure what we'd want to get added as we don't really know what you guys can add other than a few trees and bushes, etc. around the edges of our block to make it a little more "low profile" hidden from people that might be sitting on the hospital roof, zooming in with their phones for example.

If we can get that done, please contact me directly so we can talk about what can and can't be added. Please and thanks!

### Link

Here is a slight idea of what we'd want. Again, I appreciate you guys.

https://cdn.discordapp.com/attachments/968064715098038333/1064993685969850449/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064994247880753253/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064994820638122104/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064995068055920670/image.png
https://cdn.discordapp.com/attachments/895687656023920704/1064999063642181773/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064996536171372605/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064997003534291124/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064997353603473588/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064998334609227796/image.png
https://cdn.discordapp.com/attachments/968064715098038333/1064998833320370217/image.png

### Reason

The suggestion wouldn't directly be a good addition to Legacy as it's got nothing to do with others, but it would be a great addition to us, because we've gotten a little bored of how our block looked and would like to brighten it up a little if possible. It would make us hang out at the block even more than we have now (for example there is a big tower at our block that could be used really well if there were some sandbags added to it so that people can't fall off, check "Links"). We could host some group meetings there, etc. But like I said, we don't really know what can and can't be added so if we do get a green light on this, please contact me directly so that we can talk about it in depth

**Comment by DaxterPancake** [comment]
Visual changes just because it looks nice seems fine to me though I do have some issues with things being added so you can be more 'low profile' and people can't see into your block. This block is already extremely hard to get eyes on and surveillance on and I know this due to being in FIB for a long time and failing to get any good photos/angles back in CDLS days, Blancos days and also these days.

**Comment by MetaHatter** [comment]
We can take a look at it for sure, but to Daxter's point we don't really want to add things for strategic advantages. Every location has up/down sides and that's kind of part of a gang's block selection process.  We generally don't want bunkers or sniper perches since they're supposed to somewhat blend in with the area.  (Don't want to make the HOA mad).  

If we do anything to make a block/location more "secure" expect that additional things will be added elsewhere to give it vulnerabilities/FIB vantage points as well.

**Comment by MrSnowSar** [comment]
I agree with you guys, although by making the block more "low profile", I didn't mean making it a bunker. What I meant by that was that there is a few spots that lead to the block from the sides which causes us problems all the time with new people coming to it and causing issues (Dannies).

Also, with CDLS we were stationed at Amarillo Vista and not Fudge Lane. At least the "OG CDLS"?... That block is way more secure and really hard to get good photos of it like you said Daxter.. That doesn't matter though, I understand what you meant.

I appreciate your time and willingness to look into this. Let me know if you need anything. 

Thanks!

**Comment by DaxterPancake** [comment]
OG CDLS was not the only CDLS and the CDLS after you was indeed on Fudge. Which is why I used it as the example as that was the main CDLS I was looking into. 

I'd suggest making a somewhat plan or what you'd potentially want in order to make it easier for the mapping team. Such as example photos with cute little drawings and such.

**Comment by MrSnowSar** [comment]
Oh yeah, that makes sense now. We don't really like talking about the "new CDLS" for obvious reasons..

Will do. Where would you want me to post those pictures? Also, could I get a brief idea of what items can be added?

**Comment by DaxterPancake** [comment]
Here is a place you can see almost every single prop in GTA 5: https://forge.plebmasters.de/objects

You can easily place these photos onto this github suggestion.

You could also roughly state where you want a tree or a seat or something and trust the map team to sorta figure it out.

**Comment by MrSnowSar** [comment]
Perfect. Thank you so much!

**Comment by ImArteria** [comment]
Gonna be honest with you, I already made adjustments to Fudge Lane and the goal of it was not to be a fort or to make it insanely hard to hold down (this block is already very easy to hold down). The additions that I was working on is "homey" vibes to it with maybe 1-2 things to help holding it down. Spoke with Antihero about it already regarding this area.

Obviously up to the actual map devs if they wanna do so but the file I have sent over, is mainly some things to help it look nicer and a few smaller adjustments.

**Comment by MrSnowSar** [comment]
That's unfortunate... Ultimately it's up to you guys. You know what's best and I trust you. I appreciate you anyway!

**Comment by antihero6713** [comment]
pushed some updates to that block. We will roll with those and call it phase 1. closing for now
