### ISSUE TITLE
[maps/mosleys] Mosleys feedback

### ISSUE THREAD

**Issue by davidrupam** [InZidiuZ/legacy-assets-issue-tracker#719]
### Name

DaViD RuPaM#9870

### Summary

The old Mosley was quite good . But the new Mosley structure is not customer friendly , the old Mosley was a good place to chat and do RP but now as Mosley has no repair spot on front its like a storage room . I would suggest only minimum two repair spots on front and everything is good.

### Reason

Mosley is not only a business area It was a RP spot for everyone . The back side looks like storage of the mechanic with two side covered with metallic garage doors and repairing in it is not at all convincing . If we can have 2 repair spot at least on the front side RP can be done more fluently.

**Comment by antihero6713** [comment]
The mosley layout was changed due to people getting headaches at the intersection.  People would have tons of addon cars in the area and many people with addon clothing. For some peoples pc it would cause a headache coming into the south side.  In reality and lore. That front sections was used for car show room and car sales. The rear section was always the real repair bay.

**Comment by antihero6713** [comment]
closing new plans are in the works
