### ISSUE TITLE
Suggestion - Bean Machine TVs/Screens

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/legacy-assets-issue-tracker#754]
### Name

dibbey

### Summary

(Please tell me if this is the correct github, I'm so bad at these idk what I'm doing)

Ok so, I just attempted to watch a video via a tv screen in Bean Machine, however **both** TVs (while usable) display the video behind it and just vertically (not an angle for the screen). 

TV by the door: https://cdn.discordapp.com/attachments/234075458541453313/1127153131344638022/image.png
TV next to counter: https://cdn.discordapp.com/attachments/234075458541453313/1127153562821079141/image.png

### Reason

Be able to put up videos fitting for a nice Coffee Shop aesthetic or for events like how O'Malley's puts up Sports shows. 

Or for possible stuff like Karaoke or movie-nights etc., generally not a "must" fix, as you can use a TV if you really *need* it but just a nice QOL for hangouts.

**Comment by DaxterPancake** [comment]
This isn't the correct github for this, since that's a script thing. But this has been reported before and I believe it was because the TV screens in Bean Machine are a custom prop and we havn't done those yet? I could be incorrect. But also screens that tilt downwards aren't supported by our TV script.

**Comment by InZidiuZ** [comment]
Like Daxter said, we can't tilt TV screens because of an issue in FiveM, reported [here](https://forum.cfx.re/t/undesirable-behaviour-for-drawscaleform-native/4920282). I did do the TV offsets as well as I could though without tilting, [but it looks pretty bad](https://inzidiuz.com/21Dkx1.mp4). You can create a new issue if you want, asking for the models to be changed to non-tilted ones, or you can use a normal TV stand.
