### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/legacy-assets-issue-tracker#797]
### Name

HollaYalla

### Summary

Could we get a BCFD station at Rockford next to Mount Z or a Davis Station near Mosleys it would help with our response time since right now it takes like 4 minutes to get from BCFD station to the mid city but if we had a station there it would improve our response time and also improve rp since we could have certain people stationed at different places if enough BCFD r on

### Link

https://fivem.prompt-mods.com/package/4701837

### Reason

Assurance
I have read the README.md

Summary
Could we get a BCFD station at Rockford next to Mount Z or a Davis Station near Mosleys it would help with our response time since right now it takes like 4 minutes to get from BCFD station to the mid city but if we had a station there it would improve our response time and also improve rp since we could have certain people stationed at different places if enough BCFD r on

Reason
It would allow us to expand the BCFD

**Comment by COWBOI28** [comment]
If a Full Station would be too much right now a simple garage point where we can pull out our vehicles similar to what PD has near by

**Comment by CloudCait** [comment]
Rockford is already super laggy for a lot of people bc of the J store and Luxury Autos, Davis is meh cos of Mosleys. I would pick literally anywhere else lol

**Comment by COWBOI28** [comment]
> Rockford is already super laggy for a lot of people bc of the J store and Luxury Autos, Davis is meh cos of Mosleys. I would pick literally anywhere else lol

Yeah that kinda the problem Rockford and Davis are the only “centrally” located stations within the city . So I’ll talk with FD command to come to a consensus

**Comment by MetaHatter** [comment]
An additional MLO near Rockford would be too much in one spot (and that MLO is escrowed so a no go). 

I would, at most, add a garage point at Mt. Z (if one isn't there already) and/or one in the vanilla building next to St. F.  

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/84351858/f180a6c0-06ef-4d6a-a94e-59413a2ad0f2)

After all, the BC in BCFD is Blaine County so it makes sense that their custom location is up north.

**Comment by CloudTheWolf** [comment]
As per my comment on https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2987 The RP isn't really there for more than 1 main MLO currently. 

An option could be to add a garage point at St F, Davis and Rockford stations so you can quickly swap vehicles while on patrol

**Comment by COWBOI28** [comment]
> As per my comment on [InZidiuZ/op-framework-issue-tracker#2987](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2987) The RP isn't really there for more than 1 main MLO currently.
> 
> An option could be to add a garage point at St F, Davis and Rockford stations so you can quickly swap vehicles while on patrol

Yup that’s was my original point I made to command a simple garbage point would be amazing

**Comment by mastersamii** [comment]
I have talked about this several times and I believe we do not need any more custom interiors at this time I would suggest however adding three garage points. 

One to the fire station just outside of St F.

One to the fire station just outside of Mt Z.
https://cdn.discordapp.com/attachments/995517138292969482/1154243256847183912/Screenshot_2023-09-20_215445.png?ex=6539cf4d&is=65275a4d&hm=2345218da112fff7a5da11d4d06455bc1b8701ba6934d6da753eb1432929fd44&
https://cdn.discordapp.com/attachments/995517138292969482/1154243692614389780/image.png?ex=6539cfb5&is=65275ab5&hm=26459915f47ca8c8571e2e6c8317e90b2097de6012e0164dd0f416b29bfb8485&

One at the fire station just outside of Paleto hospital.

While you could argue that we have access to EMS buildings we currently have roleplay set up to make it so that neither of the departments can use the others buildings. IE the doors and garages and such because realistically they wouldn't have keys to a fire station and we wouldn't have keys to a hospital. 

I would also suggest the addition of a helicopter spot at each of these points but if that proves too difficult then we will settle with garage points.

**Comment by coalaura** [comment]
Like i said here https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2992 i don't see it making sense for the ***Blaine County*** Fire Department to have a station in the city.

**Comment by mastersamii** [comment]
I do agree we do not need another station but garage points like described I think is more what we are looking for to make it easier for us to respond to different calls.

**Comment by MetaHatter** [comment]
If it's now a request for garage points, this is not the right github.  

Submit here please:  https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose
