### ISSUE TITLE
Suggestion: Skyline R32 

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/legacy-assets-issue-tracker#85]
TwoplePop#7989 or Dean Hunt

**Summary:**
I have suggested this before on Karpenko's stream but now that I see a lot more people in the city wanting more cars like the r32 skyline or the Silvia s15, I decided to reopen it just in case there's a chance for it to be added. I know that most cars crash Karpenko's game for some reason but these cars are really solid to own.

**Link:**
R32: https://www.gta5-mods.com/search/skyline+r32

any of these would probably exite people like me a lot. 

S15: https://www.gta5-mods.com/search/s15

these cars along with maybe the s14 if these don't work would be really nice

**Reason:**
I think it would be a good addition since people like these cars irl, it would have a big impact to the racing and in general car environment in legacy rp.

**Comment by Karpenkooo** [comment]
Hey, 

You're right about the crashing issue but that's just because a lot of them aren't compactable with FiveM and would crash the whole server. I'll do my best to get some more JDMs in however you need to understand that people want Muscle, EU and other types of cars. If I was to only do a JDM pack then I can see a lot of people being upset about that. I will try to find a decent model but I can't promise anything. I'd love to add more JDM too :(

_I've tested every single S15 on https://www.gta5-mods.com/vehicles and then they all seem to crash the game or not fit my criteria_. I will, however, add this to my list of suggested cars.

_Karpenko_

_**OP_FW Asset Dev**_
