### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by LethalX-Dregs** [InZidiuZ/legacy-assets-issue-tracker#854]
### Name

LethaLX(.lethalx)

### Summary

DREGS SOCIETY Gang Legacy Roleplay Bangladesh clothing pack.

### Link

https://drive.google.com/file/d/1c2SMwBeMa2voox3GMYz8I8YmWYJb1e0E/view?usp=sharing

### Reason

This city is home to numerous gangs, each of which has a unique outfit. There is no uniform for us. We feel threatened whenever we wear any form of attire. As a result, we determined that our city need a specific dress code in order to maintain an enjoyable atmosphere.

Therefore, we request that you add these items as soon as possible.

Thank you

**Comment by DaxterPancake** [comment]
Your hoodie is just a reskinned version of the bloods hoodie that someone else made and therefore that will not be being added.
Your mask texture isn't correctly orientated in order to have the graphic shown properly either.

I'd suggest testing how your clothing looks in a local hosted server and also being creative and designing your own hoodie before this will be considered.

**Comment by LethalX-Dregs** [comment]
@DaxterPancake thanks for the feedback. I have fixed it and changed the design into a new one which I add in #857 
I hope you would be kind to add this outfit in the Legacy Bangladesh.

Thank you
