### ISSUE TITLE
Bug report Jeep Wrangler

### ISSUE THREAD

**Issue by TTVErraticAlcoholic** [InZidiuZ/legacy-assets-issue-tracker#86]
**Reporter:**
ErraticAlcoholic#7703

**Summary:**
After I bought the legendary tier Jeep Wrangler, I've noticed that there are 2 versions (different extras being used) of the vehicle when you pull them out of the garage. On top of that, one of the versions gives me issues with the back window. The back window seems to randomly open without any interaction whatsoever.

**Screenshots:**
(Extra) version 1: https://i.imgur.com/k5ZA468.jpg
(Extra) version 2: https://i.imgur.com/vkIrdUX.jpg
Randomly opening back window on version 2: https://i.gyazo.com/f7d0f9f270ed00b10094379d6e9fc3c4.mp4

**Notes:**
This is possibly related to randomized extras being used since they seem to be extras you'd usually be able to toggle I think. Just a thought.

**Comment by iGreatWhite** [comment]
Other cars do this extra thing when you pull them out it’s not a supper big issue. I would like to know about that damn window though it bugs me.

**Comment by TTVErraticAlcoholic** [comment]
Yep, I mentioned that there's more than one version exactly because of that. It's genuinely annoying. Most likely related to the model though which is why I doubt there's an easy solution :/

**Comment by TwoplePop** [comment]
I think a good solution to this would just be to allow civs to use the /extra command. There extras on the 180sx, 350z and apparently the wrangled as well. I'm sure there are more exclusive cars that have extras too.

**Comment by Karpenkooo** [comment]
Hey Guys, 
Since the only way to fix this is by using the /extra command I think that the only thing you can do is make another report on the second GitHub page as this would be a framework feature. However /extra does have many bugs and exploits that come with it. So I'm not too sure exactly on what can be done here. I will close this issue because it's no longer an asset issue. 

_**Karpenko - OP FW Assets Developer**_
