### ISSUE TITLE
[peds/?] Suggestion - More clothing for Bahama Mamas.

### ISSUE THREAD

**Issue by stardome101** [InZidiuZ/legacy-assets-issue-tracker#885]
### Name

Melody (erincaitlin)

### Summary

While attempting to create some outfits for our staff to wear during events, I noticed that our choices were _severely_ lacking. There are two, sorry to say this, _**horrid**_ shirts that are an option for us. 

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/57492114/c61ed0d2-4f31-4681-a75e-2b217ae9b939)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/57492114/59a31735-84f6-46d9-981e-ae9d15233d08)

As I was looking, I noticed that the VU has a very simple shirt that would also look fantastic with the Bahama Mamas logo on it too!
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/57492114/f2bacb38-77bf-42ad-b5b8-c174d4dd667d)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/57492114/a2bad424-3e86-46ca-9d4c-4074a77155d9)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/57492114/7377bc31-f043-4c45-bb74-ff8d439b7ee8)

Or even just a shirt that says security only...

### Reason

For clubs like mine, there is little to no customisation for the workers. For our security, I'm currently having to throw on a low-quality badge (it's kind of cute but it's not really good enough) 
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/57492114/0e8545d8-3029-42a4-8496-713f083c9b61)
While it may not make a huge impact on the rest of the server, for us who own the club and those who work there it would make a huge difference. It's currently hard to distinguish who is a worker and who is a customer, this shouldn't be the case.

Thanks for reading this long ass explanation, I hope it was put into words correctly.

**Comment by KristianRichardson** [comment]
Yes please. there isn't enough clothing for bahama mamas

**Comment by DaxterPancake** [comment]
I didn't make the 'horrid' shirts but either or, there isn't really a need to say that. Just say they don't suit the style you'd prefer.

I'm not really a fan of straight up copying another buisnesses clothing as I wish for each buisness to be unique. If you have actual designs in mind for new clothing, that would be prefered over creative freedom because that gives me anxiety that I will do something people won't like (send help). You can DM me with those designs if you wish, instead of posting here.

Also, the more 'clear and crisp' the badges or clothing become, the higher in file size it is, which is exactly what we try to avoid these days. But I can try my best.

**Comment by DaxterPancake** [comment]
Closing due to no longer owning company. Will add 'update uniforms' to my to-do for any future owners though.
