### ISSUE TITLE
Suggestion - Electric Charging Stations

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/legacy-assets-issue-tracker#904]
### Name

gadjinee

### Summary

With the high increase of electric vehicles i would like to suggest the addition of charging stations around the map, can be added in same way as cleaning stations at the gas stations 
![IMG_2801](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/124582929/1ff7149b-d6bd-4491-b5da-a31318a2ab2d)

As well as when the vehicle reaches a certain amount of miles instead of oil exchange at mechanic for all the electric vehicles adding a battery exchange 
Something like this 
![IMG_2802](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/124582929/2d924cb3-d0fa-497d-86ee-5c6b26c3eb5f)
This item can only be purchased at authorised mechanics, same way as oil that we currently have for other vehicles 

### Reason

This is more realistic for all the electric vehicle owners , makes more sense to go to charging station and charge the vehicle as well as get battery replacement after certain mileage

**Comment by coalaura** [comment]
Since you are asking for a feature not just an asset, you'd have to post this in the [script github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues). However, i don't see this working out. Not only are there only very very few people who own electric cars, but also this would be pretty complicated (making sure there is charging stations everywhere) and would generally make electric cars even less worthwile.

**Comment by coalaura** [comment]
(We haven't hand-placed each gas station and cleaning spot, they are mostly basegame)
